"""
Django settings for asistente_virtual project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url  # 👈 NUEVO

# --- SOLUCIÓN ROBUSTA PARA EVITAR EL ERROR DE LANCASTERSTEMMER EN PYTHON 3.13 ---
import builtins
try:
    from nltk.stem.lancaster import LancasterStemmer
    builtins.LancasterStemmer = LancasterStemmer
except (ImportError, AttributeError):
    from nltk.stem.snowball import SnowballStemmer
    
    class LancasterStemmerMock(SnowballStemmer):
        def __init__(self, *args, **kwargs):
            super().__init__(language='spanish')
            
    builtins.LancasterStemmer = LancasterStemmerMock
# ------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-...')

DEBUG = os.getenv('DEBUG', 'False').lower() in {'1', 'true', 'yes', 'on'}  # 👈 CAMBIADO A False por defecto

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,asistente-botchat.up.railway.app').split(',')
    if host.strip()
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',          
    'simple_chatbot',
]

# Configuración del Chatbot
SIMPLE_CHATBOT = {
    'STEMMER': 'SnowballStemmer',
    'responses': (
        ("chat.responses.SaludoResponse", "Saludo"),
        ("chat.responses.ProductoResponse", "Producto"),
        ("chat.responses.StockResponse", "Stock"),
        ("chat.responses.PrecioResponse", "Precio"),
        ("chat.responses.DespedidaResponse", "Despedida"),
        ("chat.responses.NoEntiendoResponse", "NoEntiendo"),
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'asistente_virtual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'asistente_virtual.wsgi.application'

# ============================================
# DATABASE - CONFIGURACIÓN PARA RAILWAY
# ============================================
DATABASES = {
    'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
}

MIGRATION_MODULES = {}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Configuración para Gmail 
SITE_NAME = "Asistente Farmaluz"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'farmaluz213@gmail.com'
EMAIL_HOST_PASSWORD = 'mzun urcw zxyl lavv'

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'