"""
Django settings for asistente_virtual project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
import dj_database_url 
from decouple import config
from dotenv import load_dotenv
load_dotenv()
# --- SOLUCIÓN ROBUSTA PARA EVITAR EL ERROR DE LANCASTERSTEMMER EN PYTHON 3.13 ---
import builtins
try:
    from nltk.stem.lancaster import LancasterStemmer
    builtins.LancasterStemmer = LancasterStemmer
except (ImportError, AttributeError):
    from nltk.stem.snowball import SnowballStemmer
    
    class LancasterStemmerMock(SnowballStemmer):
        def __init__(self, *args, **kwargs):
            super().__init__(language='spanish')
            
    builtins.LancasterStemmer = LancasterStemmerMock
# ------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

DEBUG = config('DEBUG', default=False, cast=bool)
SECRET_KEY = config('SECRET_KEY')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Vercel expone estos nombres automáticamente en cada deployment.
for vercel_host in (
    os.getenv('VERCEL_URL'),
    os.getenv('VERCEL_PROJECT_PRODUCTION_URL'),
):
    if vercel_host and vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_host)

# Permite el dominio de producción usado por este proyecto aunque Vercel no
# haya inyectado todavía VERCEL_PROJECT_PRODUCTION_URL.
for vercel_host in ('asistente-botchat.vercel.app', 'www.asistente-botchat.vercel.app'):
    if vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_host)

CSRF_TRUSTED_ORIGINS = [
    f'https://{host.lstrip(".")}'
    for host in ALLOWED_HOSTS
    if not host.startswith('*') and host not in ('127.0.0.1', 'localhost')
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',          
    'simple_chatbot',
]

# Configuración del Chatbot
SIMPLE_CHATBOT = {
    'STEMMER': 'SnowballStemmer',
    'responses': (
        ("chat.responses.SaludoResponse", "Saludo"),
        ("chat.responses.ProductoResponse", "Producto"),
        ("chat.responses.StockResponse", "Stock"),
        ("chat.responses.PrecioResponse", "Precio"),
        ("chat.responses.DespedidaResponse", "Despedida"),
        ("chat.responses.NoEntiendoResponse", "NoEntiendo"),
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'asistente_virtual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'asistente_virtual.wsgi.application'

# ============================================
# DATABASE
# ============================================
DATABASES = {
    'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600 # Ayuda al rendimiento manteniendo las conexiones abiertas
        )
}

MIGRATION_MODULES = {}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Email. En producción se configura desde las variables de Vercel.
SITE_NAME = os.getenv('SITE_NAME', 'Asistente Farmaluz')
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if not DEBUG else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', os.getenv('EMAIL_USERNAME', '')).strip()
# Gmail muestra las contraseñas de aplicación separadas por espacios; SMTP debe
# recibirlas sin esos espacios.
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', os.getenv('EMAIL_PASSWORD', '')).replace(' ', '').strip()
DEFAULT_FROM_EMAIL = (os.getenv('DEFAULT_FROM_EMAIL', '').strip() or EMAIL_HOST_USER)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '20'))
PUBLIC_URL = os.getenv('PUBLIC_URL', '').rstrip('/')

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use WhiteNoise to serve static files in production (useful on Vercel)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Security settings (Solo se activan en producción con DEBUG=False)

# ============================================
# CONFIGURACIONES DE SEGURIDAD (SOLO PRODUCCIÓN)
# ============================================
# ⚠️ COMENTADAS PARA DESARROLLO LOCAL
# ⚠️ DESCOMENTAR SOLO CUANDO DEBUG=False EN PRODUCCIÓN
# ============================================

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True