"""
Django settings for asistente_virtual project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# --- SOLUCIÓN ROBUSTA PARA EVITAR EL ERROR DE LANCASTERSTEMMER EN PYTHON 3.13 ---
import builtins
try:
    # Intentamos la importación tradicional por si acaso existiera en tu entorno
    from nltk.stem.lancaster import LancasterStemmer
    builtins.LancasterStemmer = LancasterStemmer
except (ImportError, AttributeError):
    # Si falla (porque ya no existe en NLTK actual), creamos un sustituto
    # basado en SnowballStemmer configurado internamente para español
    from nltk.stem.snowball import SnowballStemmer
    
    class LancasterStemmerMock(SnowballStemmer):
        def __init__(self, *args, **kwargs):
            super().__init__(language='spanish')
            
    # Engañamos a la librería inyectando nuestro sustituto con el nombre que ella busca
    builtins.LancasterStemmer = LancasterStemmerMock
# ------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=3qzs_rx$@5vm+%c52c569#o9!m)@u91!92fa3=z*3)7k3qw83')

DEBUG = os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps propias
    'chat',          
    'simple_chatbot',
]

# Configuración del Chatbot
SIMPLE_CHATBOT = {
    'STEMMER': 'SnowballStemmer',
    'responses': (
        ("chat.responses.SaludoResponse", "Saludo"),
        ("chat.responses.ProductoResponse", "Producto"),
        ("chat.responses.StockResponse", "Stock"),
        ("chat.responses.PrecioResponse", "Precio"),
        ("chat.responses.DespedidaResponse", "Despedida"),
        ("chat.responses.NoEntiendoResponse", "NoEntiendo"),
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'asistente_virtual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'asistente_virtual.wsgi.application'

# Database (Conexión MySQL Restaurada)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'inventario_farmaluz',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

MIGRATION_MODULES = {}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Configuración para Gmail 
SITE_NAME = "Asistente Farmaluz"  # Nombre que aparecerá en el correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'farmaluz213@gmail.com'  # Cambia esto
EMAIL_HOST_PASSWORD = 'mzun urcw zxyl lavv'  # Si usas Gmail, usa "Contraseña de aplicación"

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'