# Generated by Django 6.0.6 on 2026-07-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('marca', models.TextField()),
                ('codigo', models.BigIntegerField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_elab', models.DateField(blank=True, null=True)),
                ('fecha_venc', models.DateField(blank=True, null=True)),
                ('tiene_iva', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoriasNivel1',
            fields=[
                ('id_sub_categorias_nivel_1', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sub_categorias_nivel_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoriasNivel2',
            fields=[
                ('id_sub_categoria_nivel_2', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_categoria_nivel_2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sub_categorias_nivel_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('patologia', models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('hipertension', 'Hipertensión'), ('asma', 'Asma'), ('alergia', 'Alergias'), ('tiroides', 'Problemas de Tiroides'), ('otro', 'Otra')], max_length=50, null=True)),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(db_column='RIF', max_length=50, unique=True)),
                ('nombre_empresa', models.TextField(blank=True, null=True)),
                ('direccion_empresa', models.TextField(blank=True, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='ChatsOcultos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superadmin_cedula', models.CharField(max_length=50)),
                ('conversation_key', models.CharField(max_length=100)),
                ('fecha_ocultado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats_ocultos',
                'unique_together': {('superadmin_cedula', 'conversation_key')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(db_index=True, max_length=100)),
                ('sender', models.CharField(choices=[('client', 'Cliente'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat.clientes')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
