# Generated by Django 5.2.14 on 2026-05-31 23:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_detalles_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('hora', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'detalles_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('marca', models.TextField()),
                ('codigo', models.BigIntegerField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_elab', models.DateField(blank=True, null=True)),
                ('fecha_venc', models.DateField(blank=True, null=True)),
                ('tiene_iva', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(db_column='RIF', max_length=50, unique=True)),
                ('nombre_empresa', models.TextField(blank=True, null=True)),
                ('direccion_empresa', models.TextField(blank=True, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoriasNivel1',
            fields=[
                ('id_sub_categorias_nivel_1', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sub_categorias_nivel_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoriasNivel2',
            fields=[
                ('id_sub_categoria_nivel_2', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_categoria_nivel_2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sub_categorias_nivel_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.TextField(blank=True, choices=[('Pago Movil', 'Pago Movil'), ('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Tarjeta de Débito', 'Tarjeta de Débito'), ('Bancaria', 'Transferencia Bancaria'), ('Cheque', 'Cheque'), ('Bio Pago', 'Bio Pago'), ('Otro Método', 'Otro Método')], max_length=50, null=True, verbose_name='Método de Pago')),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('patologia', models.TextField(blank=True, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_key', models.CharField(db_index=True, max_length=100)),
                ('sender', models.CharField(choices=[('client', 'Cliente'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat.clientes')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
