# Generated by Django 6.0.6 on 2026-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_agregar_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
