# Generated by Django 5.1.8 on 2026-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_clientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='patologia',
            field=models.CharField(blank=True, choices=[('hipertension', 'Hipertensión'), ('diabetes', 'Diabetes'), ('oftalmologico', 'Oftalmológico'), ('pediatrico', 'Pediátrico'), ('ginecologico', 'Ginecológico'), ('otro', 'Otros')], max_length=50, null=True),
        ),
    ]
