# Generated by Django 5.1.8 on 2026-07-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_clientes_patologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='patologia',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('hipertension', 'Hipertensión'), ('asma', 'Asma'), ('alergia', 'Alergias'), ('tiroides', 'Problemas de Tiroides'), ('otro', 'Otra')], max_length=50, null=True),
        ),
    ]
