# Generated by Django 5.2 on 2026-08-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_clientes_patologia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subcategoriasnivel1',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subcategoriasnivel2',
            options={'managed': True},
        ),
    ]
