# Generated by Django 5.2 on 2026-08-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_almacen_options_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to='chat.productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.categorias'),
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.proveedores'),
        ),
        migrations.AddField(
            model_name='productos',
            name='sub_categorias_nivel_1',
            field=models.ForeignKey(blank=True, db_column='sub_categorias_nivel_1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.subcategoriasnivel1'),
        ),
        migrations.AddField(
            model_name='productos',
            name='sub_categorias_nivel_2',
            field=models.ForeignKey(blank=True, db_column='sub_categorias_nivel_2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.subcategoriasnivel2'),
        ),
        migrations.AddField(
            model_name='subcategoriasnivel1',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.categorias'),
        ),
        migrations.AddField(
            model_name='subcategoriasnivel2',
            name='sub_categoria_nivel_1',
            field=models.ForeignKey(blank=True, db_column='sub_categoria_nivel_1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.subcategoriasnivel1'),
        ),
    ]
