# Generated by Django 5.2 on 2026-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_almacen_id_producto_productos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
